# Generated by Django 5.0.3 on 2024-07-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0003_alter_collection_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='description',
        ),
    ]
