# Generated by Django 5.0.3 on 2024-10-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0004_remove_collection_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
    ]
