# Generated by Django 5.0.3 on 2024-10-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0005_alter_collection_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=256, verbose_name='Слаг'),
        ),
    ]
