# Generated by Django 5.0.3 on 2024-11-23 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0006_collection_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Коллекция', 'verbose_name_plural': 'Коллекции'},
        ),
    ]
