# Generated by Django 5.0.3 on 2024-12-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0007_alter_collection_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
