# Generated by Django 5.0.3 on 2024-06-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_price_alter_product_vat_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='priceusd',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
