# Generated by Django 5.0.3 on 2024-06-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_priceusd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='priceusd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
