# Generated by Django 5.0.3 on 2024-06-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_priceusd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='priceusd',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
