# Generated by Django 5.0.3 on 2024-07-01 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_alter_brand_category_id_alter_brand_logo_and_more'),
        ('categories', '0003_alter_category_collection_alter_category_description_and_more'),
        ('products', '0007_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brand', verbose_name='Бренд товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Категория товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Код товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mainimg',
            field=models.ImageField(blank=True, null=True, upload_to='img/products/', verbose_name='Главная картинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='package_code',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Код упаковки товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Цена товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='priceusd',
            field=models.CharField(blank=True, default=0, max_length=100, null=True, verbose_name='Цена в долларах'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество товара (не обязательно для заполнения)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_percent',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=100, null=True, verbose_name='НДС'),
        ),
    ]
