# Generated by Django 5.0.3 on 2024-07-23 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_brands_rename_brand_brandforcategory_and_more'),
        ('products', '0008_alter_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brandcategory',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='brands.brandforcategory', verbose_name='Бренд категории товара'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brands', verbose_name='Бренд'),
        ),
    ]
