# Generated by Django 5.0.3 on 2024-07-23 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_brandcategory_alter_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='brands',
        ),
    ]
