# Generated by Django 5.0.3 on 2024-08-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_brand_product_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_percent',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, verbose_name='НДС'),
        ),
    ]
