# Generated by Django 5.0.3 on 2024-08-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_discount_percent_alter_product_vat_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Процент скидки'),
        ),
    ]
