# Generated by Django 5.0.3 on 2024-08-21 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_discount_percent_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='priceusd',
        ),
    ]
