# Generated by Django 5.0.3 on 2024-08-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_popularproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popularproduct',
            options={'verbose_name': 'Популярные товары', 'verbose_name_plural': 'Популярные товары'},
        ),
        migrations.AlterField(
            model_name='popularproduct',
            name='product',
            field=models.ManyToManyField(to='products.product', verbose_name='популярные товары'),
        ),
    ]
