# Generated by Django 5.0.3 on 2024-09-29 13:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_popularproduct_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ManyToManyField(to='products.product', verbose_name='популярные товары')),
            ],
            options={
                'verbose_name': 'Товар дня',
                'verbose_name_plural': 'Товар дня',
            },
        ),
    ]
