# Generated by Django 5.0.3 on 2024-10-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_seo_key_product_title_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title_key',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Title слово для СЕО'),
        ),
    ]
