# Generated by Django 5.0.3 on 2024-10-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=256, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mainimg',
            field=models.ImageField(upload_to='img/products/', verbose_name='Главная картинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена товара'),
        ),
    ]
