# Generated by Django 5.0.3 on 2024-11-23 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_slug_alter_product_mainimg_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayproduct',
            options={'verbose_name': 'Товар дня', 'verbose_name_plural': 'Товары дня'},
        ),
        migrations.AlterModelOptions(
            name='popularproduct',
            options={'verbose_name': 'Популярный товар', 'verbose_name_plural': 'Популярные товары'},
        ),
    ]
