# Generated by Django 5.0.1 on 2024-02-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banners',
            old_name='image',
            new_name='img',
        ),
    ]
