# Generated by Django 5.0.1 on 2024-02-23 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_img', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimg',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/productIMG/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
