# Generated by Django 5.0.1 on 2024-02-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_img', '0002_alter_productimg_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimg',
            old_name='category',
            new_name='product_id',
        ),
    ]
