# Generated by Django 5.0.3 on 2024-05-04 10:20

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0004_usermodel_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.IntegerField(default=0)),
                ("delivery_address", models.CharField(blank=True, max_length=255)),
                (
                    "payment_provider",
                    models.IntegerField(
                        choices=[(0, "Unknown"), (1, "Payme"), (2, "Uzum Pay"), (3, "Uzum Nasiya")], default=0
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.usermodel")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
