# Generated by Django 5.0.3 on 2025-01-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
