# Generated by Django 5.0.3 on 2024-05-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
