# Generated by Django 5.0.3 on 2025-02-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='temp',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
