# Generated by Django 5.0.3 on 2024-05-09 17:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_order_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_provider",
        ),
    ]
