# Generated by Django 5.0.3 on 2024-08-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_phone_number_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Заказ принят'), (2, 'Заказ одобрен'), (3, 'Заказ в пути'), (4, 'Заказ доставлен')], default=1),
        ),
    ]
