# Generated by Django 5.0.3 on 2024-06-29 10:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('logo', models.ImageField(upload_to='img/installment/')),
                ('percent', models.FloatField(default=5, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
