# Generated by Django 5.0.3 on 2024-06-29 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installment',
            options={'verbose_name': 'Рассрочка', 'verbose_name_plural': 'Рассрочки'},
        ),
    ]
