# Generated by Django 5.0.3 on 2024-06-30 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0002_alter_installment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installment',
            options={},
        ),
    ]
