# Generated by Django 5.0.3 on 2024-07-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0003_alter_installment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installment',
            options={'verbose_name': 'Рассрочка', 'verbose_name_plural': 'Рассрочки'},
        ),
    ]
