# Generated by Django 5.0.3 on 2024-07-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installment', '0004_alter_installment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='logo',
            field=models.ImageField(upload_to='img/installment/', verbose_name='Логотип рассрочки'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='percent',
            field=models.FloatField(default=5, max_length=100, verbose_name='Процент рассрочки'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название рассрочки'),
        ),
    ]
