# Generated by Django 5.0.3 on 2024-09-04 11:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_remove_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(to='categories.category', verbose_name='популярные категории')),
            ],
            options={
                'verbose_name': 'Популярные категории',
                'verbose_name_plural': 'Популярные категории',
            },
        ),
    ]
