# Generated by Django 5.0.3 on 2024-09-04 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_popularcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popularcategory',
            old_name='category',
            new_name='categorys',
        ),
    ]
