# Generated by Django 5.0.3 on 2024-10-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_rename_category_popularcategory_categorys'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='seo_key',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Ключ слово для СЕО'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_key',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Ключ слово для СЕО'),
        ),
    ]
