# Generated by Django 5.0.3 on 2024-10-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_category_seo_key_category_title_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title_key',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Title слово для СЕО'),
        ),
    ]
