# Generated by Django 5.0.3 on 2024-11-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='popularcategory',
            name='categorys',
            field=models.ManyToManyField(to='categories.category', verbose_name='Популярные категории'),
        ),
    ]
