# Generated by Django 5.0.1 on 2024-02-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_alter_collection_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='image',
            new_name='img',
        ),
    ]
