# Generated by Django 5.0.3 on 2024-07-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_brand_category_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренд'},
        ),
    ]
