# Generated by Django 5.0.3 on 2024-07-01 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_alter_brand_options'),
        ('categories', '0003_alter_category_collection_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='category_id',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='категория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='img/brands/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Название на русском'),
        ),
    ]
