# Generated by Django 5.0.3 on 2024-07-23 05:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_alter_brand_category_id_alter_brand_logo_and_more'),
        ('categories', '0003_alter_category_collection_alter_category_description_and_more'),
        ('products', '0008_alter_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Название на русском')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='img/brands/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренд',
            },
        ),
        migrations.RenameModel(
            old_name='Brand',
            new_name='BrandForCategory',
        ),
        migrations.AlterModelOptions(
            name='brandforcategory',
            options={'verbose_name': 'Бренд для категории', 'verbose_name_plural': 'Бренд для категории'},
        ),
    ]
