# Generated by Django 5.0.3 on 2024-10-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0007_alter_brandforcategory_title_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandforcategory',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название на русском'),
        ),
    ]
