# Generated by Django 5.0.3 on 2024-10-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0008_alter_brandforcategory_title_alter_brands_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AddField(
            model_name='brandforcategory',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=256, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='brands',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=256, verbose_name='Слаг'),
        ),
    ]
