# Generated by Django 5.0.3 on 2024-11-23 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0009_alter_brands_options_brandforcategory_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandforcategory',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
    ]
