# Generated by Django 5.0.3 on 2024-03-21 19:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_usermodel_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usermodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
