# Generated by Django 5.0.3 on 2024-04-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_usermodel_created_at_usermodel_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
