# Generated by Django 5.0.3 on 2024-09-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usermodel_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
