# Generated by Django 5.0.3 on 2025-02-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_usermodel_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Флаг наличия премиум-аккаунта.'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='premium_end_date',
            field=models.DateTimeField(blank=True, help_text='Дата окончания премиум-подписки.', null=True),
        ),
    ]
