# Generated by Django 5.0.3 on 2025-09-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_usermodel_is_premium_usermodel_premium_end_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermodel",
            name="is_premium",
        ),
        migrations.RemoveField(
            model_name="usermodel",
            name="premium_end_date",
        ),
    ]
