# Generated by Django 5.0.3 on 2024-06-21 10:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_alter_product_price_alter_product_vat_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name1', models.CharField(max_length=512)),
                ('value1', models.CharField(max_length=512)),
                ('name2', models.CharField(max_length=512)),
                ('value2', models.CharField(max_length=512)),
                ('name3', models.CharField(max_length=512)),
                ('value3', models.CharField(max_length=512)),
                ('name4', models.CharField(max_length=512)),
                ('value4', models.CharField(max_length=512)),
                ('name5', models.CharField(max_length=512)),
                ('value5', models.CharField(max_length=512)),
                ('name6', models.CharField(max_length=512)),
                ('value6', models.CharField(max_length=512)),
                ('name7', models.CharField(max_length=512)),
                ('value7', models.CharField(max_length=512)),
                ('name8', models.CharField(max_length=512)),
                ('value8', models.CharField(max_length=512)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product'], name='characteris_product_af3662_idx')],
            },
        ),
    ]
