# Generated by Django 5.0.3 on 2024-06-21 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0002_alter_characteric_name1_alter_characteric_name2_and_more'),
        ('products', '0003_alter_product_price_alter_product_vat_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacteristicItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('value', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='characteric',
            name='characteris_product_af3662_idx',
        ),
        migrations.RemoveField(
            model_name='characteric',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='characteric',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='characteric',
            name='name3',
        ),
        migrations.RemoveField(
            model_name='characteric',
            name='name4',
        ),
        migrations.RemoveField(
            model_name='characteric',
            name='name5',
        ),
        migrations.RemoveField(
            model_name='characteric',
            name='name6',
        ),
        migrations.RemoveField(
            model_name='characteric',
            name='name7',
        ),
        migrations.RemoveField(
            model_name='characteric',
            name='name8',
        ),
        migrations.RemoveField(
            model_name='characteric',
            name='value1',
        ),
        migrations.RemoveField(
            model_name='characteric',
            name='value2',
        ),
        migrations.RemoveField(
            model_name='characteric',
            name='value3',
        ),
        migrations.RemoveField(
            model_name='characteric',
            name='value4',
        ),
        migrations.RemoveField(
            model_name='characteric',
            name='value5',
        ),
        migrations.RemoveField(
            model_name='characteric',
            name='value6',
        ),
        migrations.RemoveField(
            model_name='characteric',
            name='value7',
        ),
        migrations.RemoveField(
            model_name='characteric',
            name='value8',
        ),
        migrations.AlterField(
            model_name='characteric',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='products.product'),
        ),
        migrations.AddField(
            model_name='characteristicitem',
            name='characteristic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='characteristics.characteric'),
        ),
    ]
