# Generated by Django 5.0.3 on 2024-07-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0003_characteristicitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteric',
            options={'verbose_name': 'характеристики', 'verbose_name_plural': 'характеристики'},
        ),
        migrations.AlterModelOptions(
            name='characteristicitem',
            options={'verbose_name': 'характеристики', 'verbose_name_plural': 'характеристики'},
        ),
    ]
