# Generated by Django 5.0.3 on 2024-07-01 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0004_alter_characteric_options_and_more'),
        ('products', '0008_alter_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteric',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='products.product', verbose_name='выберите товар'),
        ),
        migrations.AlterField(
            model_name='characteristicitem',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Название характеристики'),
        ),
        migrations.AlterField(
            model_name='characteristicitem',
            name='value',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Значение характеристики'),
        ),
    ]
