# Generated by Django 5.0.3 on 2024-10-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0005_alter_characteric_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristicitem',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Название характеристики'),
        ),
        migrations.AlterField(
            model_name='characteristicitem',
            name='value',
            field=models.CharField(max_length=512, verbose_name='Значение характеристики'),
        ),
    ]
