# Generated by Django 5.0.3 on 2024-11-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0006_alter_characteristicitem_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteric',
            options={'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AddField(
            model_name='characteric',
            name='name',
            field=models.CharField(default=1, max_length=512, verbose_name='Название характеристики'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characteric',
            name='value',
            field=models.CharField(default=1, max_length=512, verbose_name='Значение характеристики'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CharacteristicItem',
        ),
    ]
