# Generated by Django 5.0.3 on 2025-02-05 10:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_usermodel_is_premium_usermodel_premium_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('duration_in_days', models.PositiveIntegerField(help_text='Срок действия тарифа в днях')),
                ('price', models.DecimalField(decimal_places=2, help_text='Стоимость тарифа', max_digits=10)),
                ('discount_percentage', models.PositiveIntegerField(default=0, help_text='Процент скидки')),
                ('discount_limit', models.DecimalField(decimal_places=2, default=0, help_text='Максимальная сумма заказа для скидки', max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='UserPremiumSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tariffs.premiumplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.usermodel')),
            ],
        ),
    ]
