# Generated by Django 5.0.3 on 2024-07-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_images', '0002_alter_productimg_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimg',
            options={'verbose_name': 'Фото товаров', 'verbose_name_plural': 'Фото товаров'},
        ),
    ]
