# Generated by Django 5.0.3 on 2024-07-01 12:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_images', '0003_alter_productimg_options'),
        ('products', '0008_alter_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimg',
            name='img',
            field=models.ImageField(null=True, upload_to='img/productIMG/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='productimg',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='выберите товар'),
        ),
    ]
