# Generated by Django 5.0.3 on 2024-11-23 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_images', '0004_alter_productimg_img_alter_productimg_product_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimg',
            options={'verbose_name': 'Фото товара', 'verbose_name_plural': 'Фото товаров'},
        ),
    ]
