# Generated by Django 5.0.3 on 2024-12-11 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_images', '0005_alter_productimg_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimg',
            name='img',
            field=models.ImageField(null=True, upload_to='img/productIMG/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Картинка'),
        ),
    ]
