# Generated by Django 5.0.3 on 2024-07-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_alter_banner_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='title_en',
        ),
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(upload_to='img/banners/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(max_length=256, verbose_name='Название на русском'),
        ),
    ]
